# Generated by Django 6.0.2 on 2026-02-14 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('organizer_type', models.CharField(max_length=50)),
                ('status', models.CharField(default='Proposed', max_length=50)),
                ('participation_type', models.CharField(max_length=50)),
                ('max_participants', models.IntegerField(default=0)),
                ('event_date', models.DateTimeField()),
                ('club', models.ForeignKey(db_column='club_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.club')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventApproval',
            fields=[
                ('event', models.OneToOneField(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='events.event')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('decision', models.CharField(max_length=20)),
                ('approved_by', models.ForeignKey(db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Event_Approvals',
            },
        ),
    ]
