# Generated by Django 6.0.2 on 2026-02-14 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_clubmember_club_alter_clubmember_user_faculty_and_more'),
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='club',
            field=models.ForeignKey(blank=True, db_column='club_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='event',
            name='organizer_type',
            field=models.CharField(choices=[('Club', 'Club'), ('Council', 'Council'), ('Department', 'Department')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='participation_type',
            field=models.CharField(choices=[('Student-only', 'Student-only'), ('Faculty-only', 'Faculty-only'), ('Joint', 'Joint')], max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('Proposed', 'Proposed'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Open', 'Open'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='Proposed', max_length=50),
        ),
        migrations.AlterField(
            model_name='eventapproval',
            name='approved_by',
            field=models.ForeignKey(blank=True, db_column='approved_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventapproval',
            name='decision',
            field=models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20),
        ),
        migrations.AlterField(
            model_name='eventapproval',
            name='event',
            field=models.OneToOneField(db_column='event_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='approval', serialize=False, to='events.event'),
        ),
    ]
