# Generated by Django 6.0.2 on 2026-02-14 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type_alter_userrole_role_and_more'),
        ('clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='club',
            field=models.ForeignKey(db_column='club_id', on_delete=django.db.models.deletion.CASCADE, related_name='members', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='club_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.OneToOneField(db_column='faculty_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='faculty_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('designation', models.CharField(blank=True, max_length=100, null=True)),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faculty_members', to='clubs.department')),
            ],
            options={
                'db_table': 'Faculty',
            },
        ),
        migrations.AlterField(
            model_name='club',
            name='faculty_coordinator_id',
            field=models.ForeignKey(blank=True, db_column='faculty_coordinator_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_clubs', to='clubs.faculty'),
        ),
    ]
